android_build:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android app
        script: |
          npx react-native run-android --variant=release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
